package io.aetherdb.raft.api;

public enum AppendEntriesReason { MATCHED, STALE_TERM, NOT_MEMBER, CONFIGURATION_MISMATCH, LOG_TOO_SHORT, TERM_MISMATCH, LOG_HASH_MISMATCH, STATE_SEQUENCE_MISMATCH, COMMITTED_CONFLICT, APPLIED_CONFLICT, LOG_STORAGE_UNAVAILABLE, FOLLOWER_BUSY, INVALID_REQUEST, SNAPSHOT_REQUIRED }
