package io.aetherdb.raft.api;

public enum VoteReason { GRANTED, STALE_TERM, ALREADY_VOTED, LOG_NOT_UP_TO_DATE, RECENT_LEADER_CONTACT, NOT_VOTER, CANDIDATE_NOT_MEMBER, CONFIGURATION_MISMATCH, LOG_HASH_MISMATCH, NODE_NOT_ELIGIBLE, STORAGE_UNAVAILABLE, INVALID_REQUEST }
