package io.aetherdb.admission;

/** Chapter 31 resource dimensions that can participate in admission decisions. */
public enum AdmissionResource {
    HEAP_BYTES,
    NATIVE_MEMTABLE_BYTES,
    BLOCK_CACHE_BYTES,
    IMMUTABLE_MEMTABLE_BYTES,
    WAL_ACTIVE_BYTES,
    WAL_RETAINED_BYTES,
    SSTABLE_LIVE_BYTES,
    COMPACTION_DEBT_BYTES,
    OPEN_FILE_COUNT,
    RPC_INBOUND_BYTES,
    RPC_OUTBOUND_BYTES,
    RPC_INFLIGHT_STREAMS,
    RAFT_LOG_UNAPPLIED_ENTRIES,
    SNAPSHOT_TRANSFER_BYTES_PER_SECOND,
    BACKUP_OPERATION_BYTES,
    BACKUP_OBJECT_COUNT,
    BACKUP_BYTES_PER_SECOND,
    THREAD_COUNT,
    VIRTUAL_THREAD_INFLIGHT
}
