package io.aetherdb.engine;

import static java.nio.charset.StandardCharsets.UTF_8;
import static org.assertj.core.api.Assertions.*;
import io.aetherdb.api.*;import io.aetherdb.api.exceptions.DatabaseOpenException;import java.io.IOException;import java.nio.file.*;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;

class PersistentAetherDatabaseTest {
 @TempDir Path temp;
 @Test void valuesAndDeletesSurviveMultipleReopens(){Path root=temp.resolve("db");try(AetherDatabase db=Aether.open(root)){db.put(b("a"),b("one"));}try(AetherDatabase db=Aether.open(root)){assertThat(text(db.get(b("a")).value())).isEqualTo("one");db.put(b("a"),b("two"));}try(AetherDatabase db=Aether.open(root)){assertThat(text(db.get(b("a")).value())).isEqualTo("two");db.delete(b("a"));}try(AetherDatabase db=Aether.open(root)){assertThat(db.get(b("a")).isFound()).isFalse();}}
 @Test void atomicBatchAndSnapshotSemanticsSurviveReopen(){Path root=temp.resolve("db");try(AetherDatabase db=Aether.open(root)){db.put(b("c"),b("old"));try(Snapshot snapshot=db.newSnapshot();WriteBatch batch=new WriteBatch()){batch.put(b("a"),b("1")).put(b("b"),b("2")).delete(b("c"));db.write(batch);assertThat(text(db.get(b("c"),snapshot).value())).isEqualTo("old");assertThat(db.get(b("c")).isFound()).isFalse();}}try(AetherDatabase db=Aether.open(root)){assertThat(text(db.get(b("a")).value())).isEqualTo("1");assertThat(text(db.get(b("b")).value())).isEqualTo("2");assertThat(db.get(b("c")).isFound()).isFalse();}}
 @Test void walOnlyRecoveryReplaysForcedAcknowledgedGroup()throws IOException{Path live=temp.resolve("live"),crash=temp.resolve("crash");AetherDatabase db=Aether.open(live);db.put(b("key"),b("wal"));copyDatabase(live,crash);db.close();try(AetherDatabase recovered=Aether.open(crash)){assertThat(text(recovered.get(b("key")).value())).isEqualTo("wal");}}
 @Test void checkpointAndNewerWalRecoverTogether()throws IOException{Path live=temp.resolve("live"),crash=temp.resolve("crash");try(AetherDatabase db=Aether.open(live)){db.put(b("old"),b("checkpoint"));}AetherDatabase db=Aether.open(live);db.put(b("new"),b("wal"));copyDatabase(live,crash);db.close();try(AetherDatabase recovered=Aether.open(crash)){assertThat(text(recovered.get(b("old")).value())).isEqualTo("checkpoint");assertThat(text(recovered.get(b("new")).value())).isEqualTo("wal");}}
 @Test void incompleteFinalWalTailIsDiscarded()throws IOException{Path root=temp.resolve("db");try(AetherDatabase db=Aether.open(root)){db.put(b("safe"),b("value"));}Path wal=Files.list(root).filter(p->p.getFileName().toString().startsWith("WAL-")).findFirst().orElseThrow();Files.write(wal,new byte[]{1,2,3,4,5},StandardOpenOption.APPEND);try(AetherDatabase db=Aether.open(root)){assertThat(text(db.get(b("safe")).value())).isEqualTo("value");}assertThat(Files.size(wal)).isGreaterThanOrEqualTo(32*1024);}
 @Test void exclusiveLockIsReleasedByIdempotentClose(){Path root=temp.resolve("db");AetherDatabase first=Aether.open(root);assertThatThrownBy(()->Aether.open(root)).isInstanceOf(DatabaseOpenException.class).hasRootCauseMessage("database lock is already held");first.close();first.close();try(AetherDatabase reopened=Aether.open(root)){assertThat(reopened.isClosed()).isFalse();}}
 @Test void corruptCurrentFailsWithoutReinitializingAndReleasesLock()throws IOException{Path root=temp.resolve("db");try(AetherDatabase database=Aether.open(root)){assertThat(database.isClosed()).isFalse();}Files.writeString(root.resolve("CURRENT"),"garbage\n");assertThatThrownBy(()->Aether.open(root)).isInstanceOf(DatabaseOpenException.class);assertThatThrownBy(()->Aether.open(root)).isInstanceOf(DatabaseOpenException.class).hasRootCauseMessage("invalid CURRENT");}
 private static byte[]b(String s){return s.getBytes(UTF_8);}private static String text(byte[]b){return new String(b,UTF_8);}private static void copyDatabase(Path from,Path to)throws IOException{Files.createDirectories(to);try(var files=Files.list(from)){for(Path source:files.toList())if(!source.getFileName().toString().equals("LOCK"))Files.copy(source,to.resolve(source.getFileName()),StandardCopyOption.REPLACE_EXISTING);}}
}
