"""Body of the notebook generated by scripts/kaggle_remote.py; runs on Kaggle."""
import hashlib
import json
import os
import shutil
import subprocess
import zipfile
from pathlib import Path

# REMOTE_CONFIG is injected as a separate notebook cell by the local preparer.
source = Path("/kaggle/input") / REMOTE_CONFIG["sourceDataset"].split("/")[1]
repo = Path("/kaggle/working/Aether-Engine")
repo.mkdir(parents=True, exist_ok=False)
archives = list(source.rglob("aether-paper-artifact.zip"))
if archives:
    if len(archives) != 1:
        raise ValueError("ambiguous source archive")
    with zipfile.ZipFile(archives[0]) as archive:
        for member in archive.infolist():
            if not (repo / member.filename).resolve().is_relative_to(repo):
                raise ValueError("source archive path escapes repository")
        archive.extractall(repo)
else:
    manifests = list(source.rglob("artifact-provenance.json"))
    if len(manifests) != 1:
        raise ValueError("source dataset has no unique artifact manifest")
    shutil.copytree(manifests[0].parent, repo, dirs_exist_ok=True)
manifest_path = repo / "artifact-provenance.json"
if hashlib.sha256(manifest_path.read_bytes()).hexdigest() != REMOTE_CONFIG["sourceManifestSha256"]:
    raise ValueError("attached source dataset differs from the locally prepared notebook")
manifest = json.loads(manifest_path.read_text())
if not manifest.get("files"):
    raise ValueError("empty source manifest")
for relative, expected in manifest["files"].items():
    path = (repo / relative).resolve()
    if not path.is_relative_to(repo) or hashlib.sha256(path.read_bytes()).hexdigest() != expected:
        raise ValueError(f"source checksum mismatch: {relative}")
subprocess.run(["bash", str(repo / "kaggle/setup.sh")], cwd=repo, check=True)
runtime = json.loads(Path("/kaggle/working/aether-paper-runtime.json").read_text())
os.environ["JAVA_HOME"] = runtime["javaHome"]
os.environ["PATH"] = runtime["javaHome"] + "/bin:" + os.environ["PATH"]
os.environ["PYTHONPATH"] = f"{repo / 'clients/python'}:{repo / 'scripts'}"
python = "/kaggle/working/aether-paper-venv/bin/python"
if REMOTE_CONFIG["mode"] == "all":
    subprocess.run([python, "-m", "pip", "install", "-r", "env/requirements-dali.lock"], cwd=repo, check=True)
subprocess.run([python, "scripts/validate_gpu.py"], cwd=repo, check=True)
results = Path("/kaggle/working/aether-results")
command = [python, "scripts/reproduce.py", REMOTE_CONFIG["mode"], "--output", str(results)]
if REMOTE_CONFIG["mode"] == "smoke":
    command += ["--training-epochs", str(REMOTE_CONFIG.get("trainingEpochs", 1))]
if REMOTE_CONFIG.get("datasetConfig"):
    command += ["--config", REMOTE_CONFIG["datasetConfig"]]
if REMOTE_CONFIG.get("scratchRoot"):
    command += ["--scratch-root", REMOTE_CONFIG["scratchRoot"]]
try:
    subprocess.run(command, cwd=repo, check=True)
finally:
    if results.exists():
        checksum = subprocess.run([python, "scripts/checksums.py", str(results)], cwd=repo)
        if checksum.returncode:
            print("Result checksum generation failed; inspect the notebook logs.")
if not results.is_dir():
    raise RuntimeError(f"Missing results directory: {results}")
result_files = [path for path in results.rglob("*") if path.is_file()]
if not result_files:
    raise RuntimeError("aether-results is empty")
archive_path = Path(shutil.make_archive("/kaggle/working/aether-results-only", "zip", root_dir=results))
if not archive_path.is_file() or archive_path.stat().st_size == 0:
    raise RuntimeError("Results archive was not created correctly")
with zipfile.ZipFile(archive_path) as archive:
    bad_file = archive.testzip()
    if bad_file is not None:
        raise RuntimeError(f"Corrupt ZIP member: {bad_file}")
    archived_files = [entry for entry in archive.infolist() if not entry.is_dir()]
if len(archived_files) != len(result_files):
    raise RuntimeError(f"Archive file-count mismatch: {len(archived_files)} archived vs {len(result_files)} source files")
print(f"Verified {len(archived_files)} files in {archive_path.name} ({archive_path.stat().st_size / 1024 ** 2:.2f} MiB)")
shutil.rmtree(results)
for temporary in (repo, Path("/kaggle/working/aether-paper-venv")):
    if temporary.exists():
        shutil.rmtree(temporary, ignore_errors=True)
print("Final Kaggle artifact:", archive_path)
