package io.aetherdb.cluster.codec;
import io.aetherdb.cluster.api.*;import io.aetherdb.format.checksum.MaskedCrc32c;import java.nio.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;
/** Canonical v2 codec for stable configurations completing membership transitions. */
public final class StableConfigurationCodecV2{
 /** Fixed v2 configuration header length. */
 public static final int HEADER_BYTES=192;private StableConfigurationCodecV2(){}
 /** Encodes and hashes a v2 stable configuration.
  * @param v configuration to encode
  * @return canonical bytes */
 public static byte[] encode(StableConfigurationV2 v){byte[] v1=StableConfigurationCodecV1.encode(new StableConfigurationV1(v.clusterId(),v.stateVersion(),v.configurationId(),v.previousHash(),v.members(),v.creationEpochMillis(),new byte[32]));byte[] out=new byte[HEADER_BYTES+v1.length-StableConfigurationCodecV1.HEADER_BYTES];ByteBuffer b=le(out);b.put("AEC2".getBytes(StandardCharsets.US_ASCII)).putShort((short)2).putShort((short)HEADER_BYTES).put((byte)1).put((byte)0).putShort((short)0).putInt(out.length);putUuid(b,v.clusterId());b.putLong(v.stateVersion());putUuid(b,v.configurationId());b.put(v.previousHash());putUuid(b,v.completedTransitionId());b.putInt(v.voters().size()).putInt(v.members().size()-v.voters().size()).putInt(v.members().size()).putInt(out.length-HEADER_BYTES).putLong(v.creationEpochMillis()).putInt(v.changedMemberCount()).putInt(0);System.arraycopy(v1,StableConfigurationCodecV1.HEADER_BYTES,out,HEADER_BYTES,v1.length-StableConfigurationCodecV1.HEADER_BYTES);byte[] hash=hash(out,136,168,188,192);if(!allZero(v.hash())&&!MessageDigest.isEqual(v.hash(),hash))throw new IllegalArgumentException("configuration hash mismatch");b.position(136).put(hash);b.putInt(188,MaskedCrc32c.masked(out,0,188));return out;}
 /** Decodes and validates a v2 stable configuration.
  * @param in canonical bytes
  * @return decoded configuration */
 public static StableConfigurationV2 decode(byte[] in){if(in==null||in.length<HEADER_BYTES)throw invalid();ByteBuffer b=le(in);byte[] m=new byte[4];b.get(m);if(!Arrays.equals(m,"AEC2".getBytes(StandardCharsets.US_ASCII))||b.getShort()!=2||b.getShort()!=HEADER_BYTES||b.get()!=1||b.get()!=0||b.getShort()!=0||b.getInt()!=in.length)throw invalid();UUID cluster=getUuid(b);long version=b.getLong();UUID id=getUuid(b);byte[] prev=get(b,32);UUID transition=getUuid(b);int voters=b.getInt(),staged=b.getInt(),count=b.getInt(),memberBytes=b.getInt();long created=b.getLong();int changed=b.getInt();if(b.getInt()!=0)throw invalid();byte[] stored=get(b,32);zero(in,168,188);if(le(in).getInt(188)!=MaskedCrc32c.masked(in,0,188)||memberBytes!=in.length-HEADER_BYTES||count!=voters+staged||!MessageDigest.isEqual(stored,hash(in,136,168,188,192)))throw invalid();byte[] fake=new byte[StableConfigurationCodecV1.HEADER_BYTES+memberBytes];ByteBuffer f=le(fake);f.put("AECF".getBytes(StandardCharsets.US_ASCII)).putShort((short)1).putShort((short)160).put((byte)1).put((byte)0).putShort((short)0).putInt(fake.length);putUuid(f,cluster);f.putLong(version);putUuid(f,id);f.put(prev).putInt(voters).putInt(staged).putInt(count).putInt(memberBytes).putLong(created);System.arraycopy(in,HEADER_BYTES,fake,160,memberBytes);byte[] h=sha(fake,112,144,156,160);f.position(112).put(h);f.putInt(156,MaskedCrc32c.masked(fake,0,156));StableConfigurationV1 parsed=StableConfigurationCodecV1.decode(fake);return new StableConfigurationV2(cluster,version,id,prev,transition,parsed.members(),created,changed,stored);}
 static byte[] hash(byte[] b,int...ranges){return sha(b,ranges);}static byte[] sha(byte[] b,int...ranges){try{byte[] c=b.clone();for(int i=0;i<ranges.length;i+=2)Arrays.fill(c,ranges[i],ranges[i+1],(byte)0);return MessageDigest.getInstance("SHA-256").digest(c);}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}static ByteBuffer le(byte[]b){return ByteBuffer.wrap(b).order(ByteOrder.LITTLE_ENDIAN);}static void putUuid(ByteBuffer b,UUID u){b.putLong(u.getMostSignificantBits()).putLong(u.getLeastSignificantBits());}static UUID getUuid(ByteBuffer b){return new UUID(b.getLong(),b.getLong());}static byte[]get(ByteBuffer b,int n){byte[]v=new byte[n];b.get(v);return v;}static void zero(byte[]b,int s,int e){for(int i=s;i<e;i++)if(b[i]!=0)throw invalid();}static boolean allZero(byte[]b){for(byte x:b)if(x!=0)return false;return true;}static IllegalArgumentException invalid(){return new IllegalArgumentException("invalid stable configuration v2");}
}
