import copy
import json

import pytest

import profile_bulk_verification as diagnostic


def report(arm, block, milliseconds=17000):
    storage = dict(tables=8, verificationPolicy="bulk-deferred-inventory-v2",
                   verification=dict(inventoryCalls=1, tablesFullyVerified=8, bytesFullyVerified=800),
                   sstableFinishes=[dict(bytes=100, stagesNs=dict(verificationOpenAndRead=1)) for _ in range(8)],
                   timingsNs=dict(verificationNs=1))
    return dict(arm=arm, blockIndex=block, samples=1200, preprocessCalls=1200,
                model=None, trainingSampleRequests=0, tensorSha256="reference",
                case=dict(backend="aether_bulk", putBatch=16, lookupBatch=16,
                          trace=False, targetSstableBytes=32 * 1024 ** 2),
                restartValidation=dict(passed=True), bulkCommit=dict(storage=storage),
                timingsMs=dict(population=milliseconds), sourceLoadAndPreprocessMs=11000)


def test_gate_requires_all_fresh_blocks_and_750ms_median_improvement():
    rows = []
    for block in range(3):
        rows.extend([report("baseline", block, 17000 + block), report("candidate", block, 16250 + block)])
    result = diagnostic.summarize(rows, 3)
    assert result["performanceGatePassed"]
    assert result["medianImprovementMs"] == 750
    assert result["arms"]["candidate"]["populationMs"]["mean"] == 16251
    assert result["arms"]["candidate"]["populationMs"]["min"] == 16250
    assert result["arms"]["candidate"]["populationMs"]["max"] == 16252
    assert not diagnostic.summarize(rows[:-1], 3)["performanceGatePassed"]
    for row in rows:
        if row["arm"] == "candidate":
            row["timingsMs"]["population"] += 1
    assert not diagnostic.summarize(rows, 3)["performanceGatePassed"]


@pytest.mark.parametrize("field,value", [("inventoryCalls", 2), ("tablesFullyVerified", 24), ("bytesFullyVerified", 2400)])
def test_duplicate_or_incomplete_verification_is_rejected(field, value):
    row = report("candidate", 0)
    diagnostic.validate_report(row, "candidate", "reference")
    row["bulkCommit"]["storage"]["verification"][field] = value
    with pytest.raises(ValueError, match="exactly once"):
        diagnostic.validate_report(row, "candidate", "reference")


def test_no_training_or_changed_configuration_is_accepted():
    row = report("candidate", 0)
    for change in (dict(model="model"), dict(samples=1199), dict(tensorSha256="wrong"), dict(trainingSampleRequests=1)):
        with pytest.raises(ValueError, match="correctness"):
            diagnostic.validate_report({**row, **change}, "candidate", "reference")
    changed = copy.deepcopy(row)
    changed["case"]["putBatch"] = 32
    with pytest.raises(ValueError, match="case protocol"):
        diagnostic.validate_report(changed, "candidate", "reference")


def test_baseline_must_have_original_verification_stages():
    row = report("baseline", 0)
    diagnostic.validate_report(row, "baseline", "reference")
    row["bulkCommit"]["storage"]["timingsNs"] = {}
    with pytest.raises(ValueError, match="frozen immediate"):
        diagnostic.validate_report(row, "baseline", "reference")


def test_frozen_baseline_rejects_file_drift(tmp_path, monkeypatch):
    current, baseline = tmp_path / "current", tmp_path / "baseline"
    for root in (current, baseline):
        (root / "scripts").mkdir(parents=True)
        for name in ("bulk_population.py", "monai_comparison.py"):
            (root / "scripts" / name).write_text("# same input semantics\n")
    files = {p.relative_to(baseline).as_posix(): diagnostic.sha256(p) for p in baseline.rglob("*.py")}
    (baseline / "artifact-provenance.json").write_text(json.dumps(dict(files=files)))
    monkeypatch.setattr(diagnostic, "ROOT", current)
    diagnostic.baseline_identity(baseline)
    generated = baseline / "build-logic/.build/fixture.class"
    generated.parent.mkdir(parents=True)
    generated.write_bytes(b"generated by the independent baseline build")
    diagnostic.baseline_identity(baseline)
    extra = baseline / "scripts/unrecorded.py"
    extra.write_text("# unrecorded source\n")
    with pytest.raises(ValueError, match="inventory changed"):
        diagnostic.baseline_identity(baseline)
    extra.unlink()
    (baseline / "scripts/bulk_population.py").write_text("# changed\n")
    with pytest.raises(ValueError, match="frozen baseline drift"):
        diagnostic.baseline_identity(baseline)


@pytest.mark.parametrize("repetitions", [1, 2, 6, 24])
def test_campaign_rejects_unfrozen_repetition_count(tmp_path, repetitions):
    with pytest.raises(ValueError, match="3-5"):
        diagnostic.run(tmp_path / "output", tmp_path / "baseline", repetitions)


@pytest.mark.parametrize("fail_worker", [False, True])
def test_paired_orchestration_preserves_failure_and_uses_isolated_sources(tmp_path, monkeypatch, fail_worker):
    import contextlib
    import os
    import subprocess
    from pathlib import Path

    current, baseline = tmp_path / "candidate", tmp_path / "baseline"
    manifest = tmp_path / "manifest.csv"
    manifest.write_text("fixed input\n")
    output, scratch = tmp_path / "results", tmp_path / "scratch"
    monkeypatch.setattr(diagnostic, "ROOT", current)
    monkeypatch.setattr(diagnostic, "baseline_identity", lambda root: {"sourceManifestSha256": "frozen"})
    monkeypatch.setattr(diagnostic, "verify", lambda root: (
        {"counts": [1200, 1260, 1323, 1389, 1458], "seed": 20260926}, [manifest]))
    monkeypatch.setattr(diagnostic, "workload_args", lambda *args: None)
    monkeypatch.setattr(diagnostic.base.workload, "load_sources", lambda args: [1])
    monkeypatch.setattr(diagnostic.base, "CanonicalTransform", lambda args: lambda item: item)
    monkeypatch.setattr(diagnostic.base, "tensor_digest", lambda values: "reference")
    monkeypatch.setattr(diagnostic, "check_capacity", lambda *args: None)

    @contextlib.contextmanager
    def campaign(root, protocol):
        root.mkdir()
        assert protocol["training"] is False and protocol["jfr"] is False
        yield {"protocolHash": "protocol", "environmentId": "host"}

    monkeypatch.setattr(diagnostic, "campaign", campaign)
    workers = []

    def worker(command, *, cwd, env, **kwargs):
        request_path = Path(command[command.index("--request") + 1])
        request = json.loads(request_path.read_text())
        arm = request["case"]["name"]
        workers.append(arm)
        assert cwd == (baseline if arm == "baseline" else current)
        assert env["PYTHONPATH"] == os.pathsep.join(str(cwd / p) for p in ("scripts", "clients/python"))
        assert "jfrFile" not in request and "layoutRegression" not in request
        store = Path(request["store"])
        store.mkdir()
        (store / "evidence").write_text("preserve on failure")
        if fail_worker and len(workers) == 3:
            raise subprocess.CalledProcessError(1, command)
        diagnostic.write_json(Path(command[command.index("--output") + 1]), report(arm, 0))

    monkeypatch.setattr(diagnostic.subprocess, "run", worker)
    if fail_worker:
        with pytest.raises(subprocess.CalledProcessError):
            diagnostic.run(output, baseline, 3, scratch)
        assert not (output / "completion.json").exists()
        assert len(list(scratch.glob("*/store/evidence"))) == 1
        assert len(list(output.glob("block-*/*/result.receipt.json"))) == 2
    else:
        diagnostic.run(output, baseline, 3, scratch)
        assert workers == ["baseline", "candidate", "candidate", "baseline", "baseline", "candidate"]
        assert json.loads((output / "summary.json").read_text())["complete"]
        assert len(list(output.glob("block-*/*/result.receipt.json"))) == 6
        assert not list(scratch.iterdir())
