package io.aetherdb.lsm.pressure;

public enum WritePressureReason { IMMUTABLE_MEMTABLES, NATIVE_CAPACITY, WAL_BYTES, LEVEL_ZERO_FILES, COMPACTION_DEBT, DISK_SPACE, BACKGROUND_FAILURE, ADMINISTRATIVE_PAUSE }
