package io.aetherdb.client.api;

public enum ClientStatus {
    OK, NOT_LEADER, LEADER_NOT_READY, NO_LEADER_KNOWN, INVALID_ARGUMENT, RESOURCE_EXHAUSTED,
    DEADLINE_EXCEEDED, INDETERMINATE, NOT_FOUND, CONFIGURATION_MISMATCH, COMMAND_ID_CONFLICT,
    ENGINE_FAILED, READ_MODE_DISABLED, SCAN_NOT_FOUND, SCAN_EXPIRED, SCAN_PAGE_MISMATCH,
    RESULT_TOO_LARGE, DATA_LOSS, UNAUTHENTICATED, PERMISSION_DENIED
}
